version: '3.7'

services:
  web:
    build: ./
    container_name: kefir_api_web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./api/api/.env
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: kefir_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./api/api/.env
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    container_name: kefir_nginx
    restart: on-failure
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data: