# Generated by Django 4.0.3 on 2022-04-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_myuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
    ]
