# Generated by Django 4.0.3 on 2022-04-12 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_myuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(max_length=120, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='additional_info',
            field=models.TextField(verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cities'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=True, verbose_name='Is Admin'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Phone'),
        ),
    ]
