# Generated by Django 4.0.3 on 2022-04-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cities_name_alter_myuser_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Additional Info'),
        ),
    ]
