# Generated by Django 4.0.3 on 2022-04-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_myuser_additional_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='name',
            new_name='city',
        ),
    ]
