version: '3.8'

services:
  web:
    build: ./
    container_name: kefir_api_web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/api
      - ./static:/usr/src/api/static
      - ./media:/usr/src/api/media
    ports:
      - 8000:8000
    env_file:
      - ./api/.env
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: kefir_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./api/.env
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    container_name: kefir_nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - web

volumes:
  postgres_data: